# Generated by Django 4.2 on 2025-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_auth",
            "0009_remove_wallet_content_type_remove_wallet_object_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Category Image",
            ),
        ),
    ]
