# Generated by Django 4.2 on 2025-09-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0011_razorpaytransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "points_required",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("deal_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "min_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("preferred_cities", models.JSONField(blank=True, default=list)),
                ("terms_conditions", models.TextField(blank=True, null=True)),
                ("is_negotiable", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom_auth.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MerchantMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Acceptance"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("match_time", models.DateTimeField(auto_now_add=True)),
                ("accepted_time", models.DateTimeField(blank=True, null=True)),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                ("agreed_points", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deal_terms", models.TextField(blank=True, null=True)),
                ("merchant1_notes", models.TextField(blank=True, null=True)),
                ("merchant2_notes", models.TextField(blank=True, null=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="custom_auth.merchantdeal",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_time"],
            },
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="owner_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Owner Name"
            ),
        ),
        migrations.CreateModel(
            name="MerchantPointsTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("points_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transfer_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transfer_time", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "from_merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_sent",
                        to="custom_auth.merchantprofile",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transfers",
                        to="custom_auth.merchantmatch",
                    ),
                ),
                (
                    "to_merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_received",
                        to="custom_auth.merchantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MerchantNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("match_request", "Match Request"),
                            ("match_accepted", "Match Accepted"),
                            ("match_rejected", "Match Rejected"),
                            ("deal_expired", "Deal Expired"),
                            ("points_transfer", "Points Transfer"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("action_data", models.JSONField(blank=True, default=dict)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="custom_auth.merchantdeal",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="custom_auth.merchantmatch",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="custom_auth.merchantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddField(
            model_name="merchantmatch",
            name="merchant1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_merchant1",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantmatch",
            name="merchant2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_merchant2",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantdeal",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals_created",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantdeal",
            name="preferred_categories",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_deals", to="custom_auth.category"
            ),
        ),
        migrations.CreateModel(
            name="MerchantSwipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "swipe_type",
                    models.CharField(
                        choices=[
                            ("right", "Right Swipe - Interested"),
                            ("left", "Left Swipe - Not Interested"),
                        ],
                        max_length=10,
                    ),
                ),
                ("swipe_time", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "counter_offer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_received",
                        to="custom_auth.merchantdeal",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_made",
                        to="custom_auth.merchantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-swipe_time"],
                "unique_together": {("merchant", "deal")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="merchantmatch",
            unique_together={("deal", "merchant1", "merchant2")},
        ),
    ]
