# Generated by Django 4.2 on 2025-09-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0012_merchantdeal_merchantmatch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealPointUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("exchange", "Point Exchange"),
                            ("discount", "Discount Applied"),
                            ("transfer", "Point Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_used", models.DecimalField(decimal_places=2, max_digits=12)),
                ("usage_description", models.TextField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MerchantDealConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmation_time", models.DateTimeField(blank=True, null=True)),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "points_exchanged",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("deal_terms", models.TextField(blank=True, null=True)),
                ("merchant1_notes", models.TextField(blank=True, null=True)),
                ("merchant2_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MerchantDealRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "points_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "counter_offer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-request_time"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="merchantswipe",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="merchantswipe",
            name="deal",
        ),
        migrations.RemoveField(
            model_name="merchantswipe",
            name="merchant",
        ),
        migrations.RenameField(
            model_name="merchantdeal",
            old_name="points_required",
            new_name="points_offered",
        ),
        migrations.RenameField(
            model_name="merchantdeal",
            old_name="min_points",
            new_name="points_remaining",
        ),
        migrations.RemoveField(
            model_name="merchantdeal",
            name="max_points",
        ),
        migrations.RemoveField(
            model_name="merchantnotification",
            name="match",
        ),
        migrations.RemoveField(
            model_name="merchantpointstransfer",
            name="match",
        ),
        migrations.AddField(
            model_name="merchantdeal",
            name="points_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="merchantdeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="merchantnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("deal_request", "Deal Request"),
                    ("deal_accepted", "Deal Accepted"),
                    ("deal_rejected", "Deal Rejected"),
                    ("deal_expired", "Deal Expired"),
                    ("points_transfer", "Points Transfer"),
                    ("system", "System Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="MerchantMatch",
        ),
        migrations.DeleteModel(
            name="MerchantSwipe",
        ),
        migrations.AddField(
            model_name="merchantdealrequest",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_requests_received",
                to="custom_auth.merchantdeal",
            ),
        ),
        migrations.AddField(
            model_name="merchantdealrequest",
            name="requesting_merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_requests_made",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantdealconfirmation",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmations",
                to="custom_auth.merchantdeal",
            ),
        ),
        migrations.AddField(
            model_name="merchantdealconfirmation",
            name="deal_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmation",
                to="custom_auth.merchantdealrequest",
            ),
        ),
        migrations.AddField(
            model_name="merchantdealconfirmation",
            name="merchant1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals_offered",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantdealconfirmation",
            name="merchant2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals_received",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="dealpointusage",
            name="confirmation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_usages",
                to="custom_auth.merchantdealconfirmation",
            ),
        ),
        migrations.AddField(
            model_name="dealpointusage",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_usages",
                to="custom_auth.merchantdeal",
            ),
        ),
        migrations.AddField(
            model_name="dealpointusage",
            name="from_merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_used_from_deals",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="dealpointusage",
            name="to_merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_received_from_deals",
                to="custom_auth.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantnotification",
            name="confirmation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="custom_auth.merchantdealconfirmation",
            ),
        ),
        migrations.AddField(
            model_name="merchantpointstransfer",
            name="confirmation",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_transfers",
                to="custom_auth.merchantdealconfirmation",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="merchantdealrequest",
            unique_together={("requesting_merchant", "deal")},
        ),
    ]
