# Generated by Django 4.2 on 2025-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0003_uservoucherredemption"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
