# Generated by Django 4.2 on 2025-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0004_voucher_purchase_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservoucherredemption",
            name="max_redemption_allowed",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uservoucherredemption",
            name="voucher_purchase_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uservoucherredemption",
            name="voucher_redemption_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
