# Generated by Django 4.2 on 2025-08-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voucher", "0005_uservoucherredemption_max_redemption_allowed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                (
                    "shared_via",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claim_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "claimed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_gift_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_card_shares",
                        to="voucher.uservoucherredemption",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
                "unique_together": {("original_purchase", "recipient_phone")},
            },
        ),
    ]
